### ISSUE TITLE
Unable to install torch with PDM_USE_UV=True

### ISSUE THREAD

**Issue by michaelze** [pdm-project/pdm#3531]
### Describe the bug

Currently (PDM 2.24.2, uv 0.7.11), it does not seem to be possible to install the torch dependency via the pytorch index. When adding a dependency to `torch` using the pytorch index, the result is a a `[KeyError]: 'hash'`.

### To reproduce

1. Create a new empty project
2. Edit the created `pyproject.toml` by adding the following lines at the bottom of the file:
    ```txt
    [[tool.uv.index]]
    name = "torch-gpu"
    url = "https://download.pytorch.org/whl/cu121"
    ```
3. Run the following command:
    ```
    PDM_USE_UV=True pdm add torch
    ```
4. Observe `[KeyError]: 'hash'`

### Expected Behavior

Adding the package should succeed.

### Environment Information

PDM version:
  2.24.2
Python Interpreter:
  /home/<redacted>/tmp/pdm-uv-test-with-pytorch/.venv/bin/python (3.10)
Project Root:
  /home/<redacted>/tmp/pdm-uv-test-with-pytorch
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.17",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.6.87.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Mon Apr 21 17:08:54 UTC 2025",
  "python_full_version": "3.10.17",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

### Verbose Command Output

Adding packages to default dependencies: torch

INFO: Using uv is experimental and might break due to uv updates.
Running uv lock command: ['/home/<redacted>/dev/python/python3.10-pdm2.24.2/bin/python3', '-m', 'uv', 'lock', '-p', '/home/<redacted>/tmp/pdm-uv-test-with-pytorch/.venv/bin/python', '--verbose', '--index-url', 'https://pypi.org/simple', '--index-strategy=unsafe-best-match', '-P', 'torch']
DEBUG uv 0.7.11
DEBUG Found workspace root: `/home/<redacted>/tmp/pdm-uv-test-with-pytorch`
DEBUG Adding root workspace member: `/home/<redacted>/tmp/pdm-uv-test-with-pytorch`
DEBUG Using Python request `/home/<redacted>/tmp/pdm-uv-test-with-pytorch/.venv/bin/python` from explicit request
DEBUG Checking for Python environment at `.venv`
DEBUG The project environment's Python version satisfies the request: `path `.venv/bin/python``
DEBUG Using request timeout of 30s
DEBUG Ignoring existing lockfile due to `--upgrade-package`
DEBUG Found static `pyproject.toml` for: pdm-uv-test-with-pytorch @ file:///home/<redacted>/tmp/pdm-uv-test-with-pytorch
DEBUG No workspace root found, using project root
DEBUG Solving with installed Python version: 3.10.17
DEBUG Solving with target Python version: ==3.10.*
DEBUG Adding direct dependency: pdm-uv-test-with-pytorch*
DEBUG Searching for a compatible version of pdm-uv-test-with-pytorch @ file:///home/<redacted>/tmp/pdm-uv-test-with-pytorch (*)
DEBUG Adding direct dependency: torch*
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/torch/
DEBUG Found stale response for: https://pypi.org/simple/torch/
DEBUG Sending revalidation request for: https://pypi.org/simple/torch/
DEBUG Found not-modified response for: https://pypi.org/simple/torch/
DEBUG Searching for a compatible version of torch (*)
DEBUG Selecting: torch==2.7.1 [compatible] (torch-2.7.1-cp310-cp310-manylinux_2_28_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/6a/27/2e06cb52adf89fe6e020963529d17ed51532fc73c1e6d1b18420ef03338c/torch-2.7.1-cp310-cp310-manylinux_2_28_aarch64.whl.metadata
DEBUG Adding transitive dependency for torch==2.7.1: filelock*
DEBUG Adding transitive dependency for torch==2.7.1: fsspec*
DEBUG Adding transitive dependency for torch==2.7.1: jinja2*
DEBUG Adding transitive dependency for torch==2.7.1: networkx*
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.4.1, <12.6.4.1+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.80, <12.6.80+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.77, <12.6.77+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.77, <12.6.77+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=9.5.1.17, <9.5.1.17+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=11.3.0.4, <11.3.0.4+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=1.11.1.6, <1.11.1.6+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=10.3.7.77, <10.3.7.77+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=11.7.1.2, <11.7.1.2+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.5.4.2, <12.5.4.2+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=0.6.3, <0.6.3+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=2.26.2, <2.26.2+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.85, <12.6.85+
DEBUG Adding transitive dependency for torch==2.7.1: nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}>=12.6.77, <12.6.77+
DEBUG Adding transitive dependency for torch==2.7.1: sympy>=1.13.3
DEBUG Adding transitive dependency for torch==2.7.1: triton{platform_machine == 'x86_64' and sys_platform == 'linux'}>=3.3.1, <3.3.1+
DEBUG Adding transitive dependency for torch==2.7.1: typing-extensions>=4.10.0
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/networkx/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cudnn-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cusparselt-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/sympy/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/filelock/
DEBUG Found fresh response for: https://pypi.org/simple/filelock/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/fsspec/
DEBUG Found fresh response for: https://pypi.org/simple/fsspec/
DEBUG Found fresh response for: https://pypi.org/simple/jinja2/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/jinja2/
DEBUG Found fresh response for: https://pypi.org/simple/networkx/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cublas-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cublas-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cuda-cupti-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-cupti-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cuda-nvrtc-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-nvrtc-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cuda-runtime-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-runtime-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cudnn-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cufft-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cufft-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cufile-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cufile-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-curand-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-curand-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cusolver-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cusolver-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-cusparse-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cusparse-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cusparselt-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-nccl-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nccl-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-nvjitlink-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nvjitlink-cu12/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/nvidia-nvtx-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nvtx-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/sympy/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/triton/
DEBUG Found fresh response for: https://pypi.org/simple/triton/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/typing-extensions/
DEBUG Found fresh response for: https://pypi.org/simple/typing-extensions/
DEBUG No netrc file found
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/a2/09/77d55d46fd61b4a135c444fc97158ef34a095e5681d0a6c10b75bf356191/sympy-1.14.0-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/4d/36/2a115987e2d8c300a974597416d9de88f2444426de9571f4b59b2cca3acc/filelock-3.18.0-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/bb/61/78c7b3851add1481b048b5fdc29067397a1784e2910592bc81bb3f608635/fsspec-2025.5.1-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.4.1, <12.6.4.1+)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-cublas-cu12==12.6.4.1: nvidia-cublas-cu12==12.6.4.1
DEBUG Adding transitive dependency for nvidia-cublas-cu12==12.6.4.1: nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.4.1
DEBUG Searching for a compatible version of nvidia-cublas-cu12 (==12.6.4.1)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/af/eb/ff4b8c503fa1f1796679dce648854d58751982426e4e4b37d6fce49d259c/nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.4.1)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.80, <12.6.80+)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cuda-cupti-cu12==12.6.80: nvidia-cuda-cupti-cu12==12.6.80
DEBUG Adding transitive dependency for nvidia-cuda-cupti-cu12==12.6.80: nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.80
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12 (==12.6.80)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/e6/8b/2f6230cb715646c3a9425636e513227ce5c93c4d65823a734f4bb86d43c3/nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.80)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cuda-nvrtc-cu12==12.6.77: nvidia-cuda-nvrtc-cu12==12.6.77
DEBUG Adding transitive dependency for nvidia-cuda-nvrtc-cu12==12.6.77: nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.77
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12 (==12.6.77)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/f4/2f/72df534873235983cc0a5371c3661bebef7c4682760c275590b972c7b0f9/nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cuda-runtime-cu12==12.6.77: nvidia-cuda-runtime-cu12==12.6.77
DEBUG Adding transitive dependency for nvidia-cuda-runtime-cu12==12.6.77: nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.77
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12 (==12.6.77)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/8f/ea/590b2ac00d772a8abd1c387a92b46486d2679ca6622fd25c18ff76265663/nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=9.5.1.17, <9.5.1.17+)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.5.1.17: nvidia-cudnn-cu12==9.5.1.17
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.5.1.17: nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==9.5.1.17
DEBUG Searching for a compatible version of nvidia-cudnn-cu12 (==9.5.1.17)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/99/93/a201a12d3ec1caa8c6ac34c1c2f9eeb696b886f0c36ff23c638b46603bd0/nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.5.1.17: nvidia-cublas-cu12*
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==9.5.1.17)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.5.1.17: nvidia-cublas-cu12*
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=11.3.0.4, <11.3.0.4+)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.3.0.4: nvidia-cufft-cu12==11.3.0.4
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.3.0.4: nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==11.3.0.4
DEBUG Searching for a compatible version of nvidia-cufft-cu12 (==11.3.0.4)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/1f/37/c50d2b2f2c07e146776389e3080f4faf70bcc4fa6e19d65bb54ca174ebc3/nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.3.0.4: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==11.3.0.4)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.3.0.4: nvidia-nvjitlink-cu12*
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/69/e0/552843e0d356fbb5256d21449fa957fa4eff3bbc135a74a691ee70c7c5da/typing_extensions-4.14.0-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=1.11.1.6, <1.11.1.6+)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-cufile-cu12==1.11.1.6: nvidia-cufile-cu12==1.11.1.6
DEBUG Adding transitive dependency for nvidia-cufile-cu12==1.11.1.6: nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==1.11.1.6
DEBUG Searching for a compatible version of nvidia-cufile-cu12 (==1.11.1.6)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b2/66/cc9876340ac68ae71b15c743ddb13f8b30d5244af344ec8322b449e35426/nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==1.11.1.6)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=10.3.7.77, <10.3.7.77+)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-curand-cu12==10.3.7.77: nvidia-curand-cu12==10.3.7.77
DEBUG Adding transitive dependency for nvidia-curand-cu12==10.3.7.77: nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==10.3.7.77
DEBUG Searching for a compatible version of nvidia-curand-cu12 (==10.3.7.77)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/42/ac/36543605358a355632f1a6faa3e2d5dfb91eab1e4bc7d552040e0383c335/nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==10.3.7.77)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=11.7.1.2, <11.7.1.2+)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cusolver-cu12==11.7.1.2
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==11.7.1.2
DEBUG Searching for a compatible version of nvidia-cusolver-cu12 (==11.7.1.2)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/93/17/dbe1aa865e4fdc7b6d4d0dd308fdd5aaab60f939abfc0ea1954eac4fb113/nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cublas-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cusparse-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==11.7.1.2)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cublas-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-cusparse-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.7.1.2: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.5.4.2, <12.5.4.2+)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.5.4.2: nvidia-cusparse-cu12==12.5.4.2
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.5.4.2: nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.5.4.2
DEBUG Searching for a compatible version of nvidia-cusparse-cu12 (==12.5.4.2)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/94/a8/527f641cf3094d5ab550f820c7cfa71d81f472523bb289e6962a6aa79b45/nvidia_cusparse_cu12-12.5.9.5-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/eb/eb/6681efd0aa7df96b4f8067b3ce7246833dd36830bb4cec8896182773db7d/nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.5.4.2: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.5.4.2)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.5.4.2: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=0.6.3, <0.6.3+)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusparselt-cu12==0.6.3: nvidia-cusparselt-cu12==0.6.3
DEBUG Adding transitive dependency for nvidia-cusparselt-cu12==0.6.3: nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==0.6.3
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12 (==0.6.3)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/86/69/01de7245968084eb73e50512daa72b36e27dfd2994bf268e6a205eff5093/nvidia_nvjitlink_cu12-12.9.41-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/62/da/4de092c61c6dea1fc9c936e69308a02531d122e12f1f649825934ad651b5/nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==0.6.3)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=2.26.2, <2.26.2+)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-nccl-cu12==2.26.2: nvidia-nccl-cu12==2.26.2
DEBUG Adding transitive dependency for nvidia-nccl-cu12==2.26.2: nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==2.26.2
DEBUG Searching for a compatible version of nvidia-nccl-cu12 (==2.26.2)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/69/5b/ca2f213f637305633814ae8c36b153220e40a07ea001966dcd87391f3acb/nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==2.26.2)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.85, <12.6.85+)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-nvjitlink-cu12==12.6.85: nvidia-nvjitlink-cu12==12.6.85
DEBUG Adding transitive dependency for nvidia-nvjitlink-cu12==12.6.85: nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.85
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12 (==12.6.85)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/9d/d7/c5383e47c7e9bf1c99d5bd2a8c935af2b6d705ad831a7ec5c97db4d82f4f/nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.85)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-nvtx-cu12==12.6.77: nvidia-nvtx-cu12==12.6.77
DEBUG Adding transitive dependency for nvidia-nvtx-cu12==12.6.77: nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'}==12.6.77
DEBUG Searching for a compatible version of nvidia-nvtx-cu12 (==12.6.77)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b9/93/80f8a520375af9d7ee44571a6544653a176e53c2b8ccce85b97b83c2491b/nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of triton{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=3.3.1, <3.3.1+)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Adding transitive dependency for triton==3.3.1: triton==3.3.1
DEBUG Adding transitive dependency for triton==3.3.1: triton{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.1
DEBUG Searching for a compatible version of triton (==3.3.1)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Found stale response for: https://download.pytorch.org/whl/triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata
DEBUG Found not-modified response for: https://download.pytorch.org/whl/triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata
DEBUG Adding transitive dependency for triton==3.3.1: setuptools>=40.8.0
DEBUG Searching for a compatible version of triton{platform_machine == 'x86_64' and sys_platform == 'linux'} (==3.3.1)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Adding transitive dependency for triton==3.3.1: setuptools>=40.8.0
DEBUG Searching for a compatible version of filelock (*)
DEBUG Selecting: filelock==3.18.0 [compatible] (filelock-3.18.0-py3-none-any.whl)
DEBUG Searching for a compatible version of fsspec (*)
DEBUG Selecting: fsspec==2025.5.1 [compatible] (fsspec-2025.5.1-py3-none-any.whl)
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Selecting: jinja2==3.1.6 [compatible] (jinja2-3.1.6-py3-none-any.whl)
DEBUG Adding transitive dependency for jinja2==3.1.6: markupsafe>=2.0
DEBUG Searching for a compatible version of networkx (*)
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/setuptools/
DEBUG No compatible version found for: Python
DEBUG Recording unit propagation conflict of Python from incompatibility of (networkx)
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.4.1, <12.6.4.1+)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-cublas-cu12 (==12.6.4.1)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.4.1)
DEBUG Selecting: nvidia-cublas-cu12==12.6.4.1 [compatible] (nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.80, <12.6.80+)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12 (==12.6.80)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.80)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.6.80 [compatible] (nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12 (==12.6.77)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.6.77 [compatible] (nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12 (==12.6.77)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.6.77 [compatible] (nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=9.5.1.17, <9.5.1.17+)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cudnn-cu12 (==9.5.1.17)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==9.5.1.17)
DEBUG Selecting: nvidia-cudnn-cu12==9.5.1.17 [compatible] (nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=11.3.0.4, <11.3.0.4+)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cufft-cu12 (==11.3.0.4)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==11.3.0.4)
DEBUG Selecting: nvidia-cufft-cu12==11.3.0.4 [compatible] (nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=1.11.1.6, <1.11.1.6+)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/markupsafe/
DEBUG Searching for a compatible version of nvidia-cufile-cu12 (==1.11.1.6)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-cufile-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==1.11.1.6)
DEBUG Selecting: nvidia-cufile-cu12==1.11.1.6 [compatible] (nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=10.3.7.77, <10.3.7.77+)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-curand-cu12 (==10.3.7.77)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==10.3.7.77)
DEBUG Selecting: nvidia-curand-cu12==10.3.7.77 [compatible] (nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=11.7.1.2, <11.7.1.2+)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusolver-cu12 (==11.7.1.2)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==11.7.1.2)
DEBUG Selecting: nvidia-cusolver-cu12==11.7.1.2 [compatible] (nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.5.4.2, <12.5.4.2+)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparse-cu12 (==12.5.4.2)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.5.4.2)
DEBUG Selecting: nvidia-cusparse-cu12==12.5.4.2 [compatible] (nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=0.6.3, <0.6.3+)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12 (==0.6.3)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusparselt-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==0.6.3)
DEBUG Selecting: nvidia-cusparselt-cu12==0.6.3 [compatible] (nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=2.26.2, <2.26.2+)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nccl-cu12 (==2.26.2)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==2.26.2)
DEBUG Selecting: nvidia-nccl-cu12==2.26.2 [compatible] (nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.85, <12.6.85+)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12 (==12.6.85)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.85)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.6.85 [compatible] (nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=12.6.77, <12.6.77+)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nvtx-cu12 (==12.6.77)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and sys_platform == 'linux'} (==12.6.77)
DEBUG Selecting: nvidia-nvtx-cu12==12.6.77 [compatible] (nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl)
DEBUG Searching for a compatible version of triton{platform_machine == 'x86_64' and sys_platform == 'linux'} (>=3.3.1, <3.3.1+)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of triton (==3.3.1)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of triton{platform_machine == 'x86_64' and sys_platform == 'linux'} (==3.3.1)
DEBUG Selecting: triton==3.3.1 [compatible] (triton-3.3.1-cp310-cp310-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl)
DEBUG Searching for a compatible version of filelock (*)
DEBUG Selecting: filelock==3.18.0 [compatible] (filelock-3.18.0-py3-none-any.whl)
DEBUG Searching for a compatible version of fsspec (*)
DEBUG Selecting: fsspec==2025.5.1 [compatible] (fsspec-2025.5.1-py3-none-any.whl)
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Selecting: jinja2==3.1.6 [compatible] (jinja2-3.1.6-py3-none-any.whl)
DEBUG Searching for a compatible version of networkx (<3.5 | >3.5)
DEBUG Selecting: networkx==3.4.2 [compatible] (networkx-3.4.2-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://pypi.org/simple/markupsafe/
DEBUG Searching for a compatible version of sympy (>=1.13.3)
DEBUG Selecting: sympy==1.14.0 [compatible] (sympy-1.14.0-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.14.0: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of typing-extensions (>=4.10.0)
DEBUG Selecting: typing-extensions==4.14.0 [compatible] (typing_extensions-4.14.0-py3-none-any.whl)
DEBUG No cache entry for: https://download.pytorch.org/whl/cu121/mpmath/
DEBUG Found fresh response for: https://pypi.org/simple/setuptools/
DEBUG Found fresh response for: https://pypi.org/simple/mpmath/
DEBUG Searching for a compatible version of setuptools (>=40.8.0)
DEBUG Selecting: setuptools==80.9.0 [compatible] (setuptools-80.9.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/a3/dc/17031897dae0efacfea57dfd3a82fdd2a2aeb58e0ff71b77b87e44edc772/setuptools-80.9.0-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of markupsafe (>=2.0)
DEBUG Selecting: markupsafe==3.0.2 [compatible] (MarkupSafe-3.0.2-cp310-cp310-macosx_10_9_universal2.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/04/90/d08277ce111dd22f77149fd1a5d4653eeb3b3eaacbdfcbae5afb2600eebd/MarkupSafe-3.0.2-cp310-cp310-macosx_10_9_universal2.whl.metadata
DEBUG Searching for a compatible version of mpmath (>=1.1.0, <1.4)
DEBUG Selecting: mpmath==1.3.0 [compatible] (mpmath-1.3.0-py3-none-any.whl)
DEBUG Found stale response for: https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl
DEBUG Found not-modified response for: https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl
DEBUG Tried 26 versions: filelock 1, fsspec 1, jinja2 1, markupsafe 1, mpmath 1, networkx 1, nvidia-cublas-cu12 1, nvidia-cuda-cupti-cu12 1, nvidia-cuda-nvrtc-cu12 1, nvidia-cuda-runtime-cu12 1, nvidia-cudnn-cu12 1, nvidia-cufft-cu12 1, nvidia-cufile-cu12 1, nvidia-curand-cu12 1, nvidia-cusolver-cu12 1, nvidia-cusparse-cu12 1, nvidia-cusparselt-cu12 1, nvidia-nccl-cu12 1, nvidia-nvjitlink-cu12 1, nvidia-nvtx-cu12 1, pdm-uv-test-with-pytorch 1, setuptools 1, sympy 1, torch 1, triton 1, typing-extensions 1
DEBUG all marker environments resolution took 1.512s
Resolved 26 packages in 1.51s
Added filelock v3.18.0
Added fsspec v2025.5.1
Added jinja2 v3.1.6
Added markupsafe v3.0.2
Added mpmath v1.3.0
Added networkx v3.4.2
Added nvidia-cublas-cu12 v12.6.4.1
Added nvidia-cuda-cupti-cu12 v12.6.80
Added nvidia-cuda-nvrtc-cu12 v12.6.77
Added nvidia-cuda-runtime-cu12 v12.6.77
Added nvidia-cudnn-cu12 v9.5.1.17
Added nvidia-cufft-cu12 v11.3.0.4
Added nvidia-cufile-cu12 v1.11.1.6
Added nvidia-curand-cu12 v10.3.7.77
Added nvidia-cusolver-cu12 v11.7.1.2
Added nvidia-cusparse-cu12 v12.5.4.2
Added nvidia-cusparselt-cu12 v0.6.3
Added nvidia-nccl-cu12 v2.26.2
Added nvidia-nvjitlink-cu12 v12.6.85
Added nvidia-nvtx-cu12 v12.6.77
Added setuptools v80.9.0
Added sympy v1.14.0
Added torch v2.7.1
Added triton v3.3.1
Added typing-extensions v4.14.0

Traceback (most recent call last):
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/core.py", line 391, in main
    return core.main(args or sys.argv[1:])
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/core.py", line 270, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/core.py", line 265, in main
    self.handle(project, options)
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/core.py", line 195, in handle
    command.handle(project, options)
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 71, in handle
    self.do_add(
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/cli/actions.py", line 134, in do_lock
    resolved, collected_groups = resolver.resolve()
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/resolver/uv.py", line 192, in resolve
    return self._parse_uv_lock(uv_lock_path)
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/resolver/uv.py", line 161, in _parse_uv_lock
    candidate.hashes.append(hash_maker(wheel))
  File "/home/<redacted>/dev/python/python3.10-pdm2.24.2/lib/python3.10/site-packages/pdm/resolver/uv.py", line 158, in hash_maker
    return {"file": Link(item["url"]).filename, "hash": item["hash"]}
KeyError: 'hash'

### Additional Context

As per astral-sh/uv#5166, `uv.lock` files do not seem to always contain hashes for packages. In my case, there does not seem to be a hash in the `uv.lock` file for the `triton` package. The relevant section from the `uv.lock` file looks like this:

```
[[package]]
name = "triton"
version = "3.3.1"
source = { registry = "https://download.pytorch.org/whl/cu121" }
dependencies = [
    { name = "setuptools" },
]
wheels = [
    { url = "https://download.pytorch.org/whl/triton-3.3.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl" },
]
```

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.

**Comment by michaelze** [comment]
Just tested the fix today with the release 2.25.0 and it works perfectly. Thanks a lot for your constant efforts 🥇
